---
apiVersion: v1
kind: Service
metadata:
  name: kfp
  namespace: kubeflow
spec:
  type: NodePort
  selector:
    app: ml-pipeline
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30088
---
apiVersion: v1
kind: Service
metadata:
  name: kfp-ui
  namespace: kubeflow
spec:
  type: NodePort
  selector:
    app: ml-pipeline-ui
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
