// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APILongValues api long values
//
// swagger:model apiLongValues
type APILongValues struct {

	// values
	Values []string `json:"values"`
}

// Validate validates this api long values
func (m *APILongValues) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api long values based on context it is used
func (m *APILongValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APILongValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APILongValues) UnmarshalBinary(b []byte) error {
	var res APILongValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
