// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIIntValues api int values
//
// swagger:model apiIntValues
type APIIntValues struct {

	// values
	Values []int32 `json:"values"`
}

// Validate validates this api int values
func (m *APIIntValues) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api int values based on context it is used
func (m *APIIntValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIIntValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIIntValues) UnmarshalBinary(b []byte) error {
	var res APIIntValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
