// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PredicateOp Op is the operation to apply.
//
//  - EQUALS: Operators on scalar values. Only applies to one of |int_value|,
// |long_value|, |string_value| or |timestamp_value|.
//  - IN: Checks if the value is a member of a given array, which should be one of
// |int_values|, |long_values| or |string_values|.
//  - IS_SUBSTRING: Checks if the value contains |string_value| as a substring match. Only
// applies to |string_value|.
//
// swagger:model PredicateOp
type PredicateOp string

func NewPredicateOp(value PredicateOp) *PredicateOp {
	v := value
	return &v
}

const (

	// PredicateOpUNKNOWN captures enum value "UNKNOWN"
	PredicateOpUNKNOWN PredicateOp = "UNKNOWN"

	// PredicateOpEQUALS captures enum value "EQUALS"
	PredicateOpEQUALS PredicateOp = "EQUALS"

	// PredicateOpNOTEQUALS captures enum value "NOT_EQUALS"
	PredicateOpNOTEQUALS PredicateOp = "NOT_EQUALS"

	// PredicateOpGREATERTHAN captures enum value "GREATER_THAN"
	PredicateOpGREATERTHAN PredicateOp = "GREATER_THAN"

	// PredicateOpGREATERTHANEQUALS captures enum value "GREATER_THAN_EQUALS"
	PredicateOpGREATERTHANEQUALS PredicateOp = "GREATER_THAN_EQUALS"

	// PredicateOpLESSTHAN captures enum value "LESS_THAN"
	PredicateOpLESSTHAN PredicateOp = "LESS_THAN"

	// PredicateOpLESSTHANEQUALS captures enum value "LESS_THAN_EQUALS"
	PredicateOpLESSTHANEQUALS PredicateOp = "LESS_THAN_EQUALS"

	// PredicateOpIN captures enum value "IN"
	PredicateOpIN PredicateOp = "IN"

	// PredicateOpISSUBSTRING captures enum value "IS_SUBSTRING"
	PredicateOpISSUBSTRING PredicateOp = "IS_SUBSTRING"
)

// for schema
var predicateOpEnum []interface{}

func init() {
	var res []PredicateOp
	if err := json.Unmarshal([]byte(`["UNKNOWN","EQUALS","NOT_EQUALS","GREATER_THAN","GREATER_THAN_EQUALS","LESS_THAN","LESS_THAN_EQUALS","IN","IS_SUBSTRING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		predicateOpEnum = append(predicateOpEnum, v)
	}
}

func (m PredicateOp) validatePredicateOpEnum(path, location string, value PredicateOp) error {
	if err := validate.EnumCase(path, location, value, predicateOpEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this predicate op
func (m PredicateOp) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePredicateOpEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this predicate op based on context it is used
func (m PredicateOp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
